name: Deploy Mautic to DigitalOcean

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Mautic
      uses: escopecz/mautic-do-action@0.2.0
      with:
        vps-name: ${{ github.event.inputs.vps_name || vars.VPS_NAME || format('mautic-{0}', github.ref_name) }}
        vps-size: 's-1vcpu-1gb'
        vps-region: 'ams3'
        domain: ''
        email: ${{ vars.EMAIL_ADDRESS }}
        mautic-password: ${{ secrets.MAUTIC_PASSWORD }}
        mysql-password: ${{ secrets.MYSQL_PASSWORD }}
        mysql-root-password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        digitalocean-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        mautic-port: '8001'
